### ISSUE TITLE
Export types so they can be used by upstream components

### ISSUE THREAD

**Issue by nickradford** [bradgarropy/next-seo#2]
Say I have a `<Page />` component, which will use the `<SEO />` component inside of it - I would like to reference the types that the SEO component is expecting in the parent component as a prop.

```tsx
type PageProps = {
    children: JSX.Element;
    seo: SEOProps;
}
```

As a temp workaround, I've added this into my project, but in case next-seo adds features in the future, it would also be nice to just use the same props.

```ts
export type SEOProps = {
  title?: string;
  description?: string;
  keywords?: string[];
  icon?: string;
  facebook?: {
    image?: string;
    url?: string;
    type?: string;
  };
  twitter?: {
    image?: string;
    site?: string;
    card?: string;
  };
};
```

**Comment by bradgarropy** [comment]
@all-contributors please add @nickradford for bugs
